FORMAT: 1A
HOST: http://api.sdisdebts.com

# SDIS Debts API
SDIS Debts API is a service to track and optimize debts between a group of friends.

## Authentication
Currently the SDIS Debts API does not provide authenticated access.
Authentication will be implemented using OAuth, with logins by username and password, Facebook, Google and other services.

## Digital Signature
To prevent tampering of the data, a digital signature is included as a query parameter in the resources' URI.

## Media Types
Where applicable this API uses the JSON media-type to represent resources states and affordances.

Requests with a message-body are using plain JSON to set or update resource states.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

# SDIS Debts API Root [/]
SDIS Debts API entry point.

This resource does not have any attributes.

## Retrieve the Entry Point [GET]

+ Response 204

# Group User
Users related resources of the **SDIS Debts API**

## User [/users/{id}{?checksum}]
A single User object. The User resource is the central resource in the SDIS Debts API. It represents one user of the service.

The User resource has the following attributes:

- id -- Username of the User
- email -- Email of the User

+ Parameters
    + id (string, required, `john`) ... ID of the User
    + checksum (string, required, `abcd`) ... Digital signature of the id

+ Model (application/json)

    ```js
    {
        "id": "johndoe",
        "email": "johndoe@example.com"
    }
    ```

### Retrieve a single User [GET]
This method is only available for the authenticated user.

+ Response 200 (application/json)

    [User][]

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

+ Response 404 (application/json)

        { "error": "User 'johndoe' does not exist." }

### Delete a User [DELETE]
This method is only available for the authenticated user.

+ Response 204

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

+ Response 404 (application/json)

        { "error": "User 'johndoe' does not exist." }

## Debt [/users/{id}/debts/{debtId}{?checksum}]
A single Debt object. The Debt resource represents a debt that a User has on another User.

A positive *value* means that this User owes something to another Used, a negative *value* means that this User is owed by another User.

The Debt resource has the following attributes:

- debtId -- Id of a Debt of a User (read-only)
- user -- User that we owe or are owed by (read-only)
- value -- Money that we owe or are owed by the User above
- date -- Date (ISO 8601) the Debt was created (read-only)
- resolved -- Boolean, true if the debt was paid, false otherwise

+ Parameters
    + id (string, required, `john`) ... ID of the User
    + debtId (number, required, `1`) ... ID of the Debt of a User
    + checksum (string, required, `abcd`) ... Digital signature of the id and debtId

+ Model (application/json)

    ```js
    {
        "debtId": 1,
        "user": "janeroe",
        "value": 100,
        "date": "2014-04-14T11:29Z",
        "resolved": false
    }
    ```

### Retrieve a single Debt [GET]
This method is only available for the authenticated user.

+ Response 200 (application/json)

    [Debt][]

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

+ Response 404 (application/json)

        { "error": "Debt '2' for user 'johndoe' does not exist." }

### Update a single Debt [PATCH]
This method is only available for the authenticated user.
Modifiable fields are *value* and *resolved*.

+ Parameters

    + checksum (string, required, `abcd`) ... Digital signature of the value and/or resolved

+ Request (application/json)

        {
            "resolved": false
        }

+ Response 200 (application/json)

    [Debt][]

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Cannot update field 'whatever'" }
        or
        { "error": "Invalid checksum" }

+ Response 404 (application/json)

        { "error": "Debt '2' for user 'johndoe' does not exist." }

### Delete a Debt [DELETE]
This method is only available for the authenticated user.

+ Response 204

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

+ Response 404 (application/json)

        { "error": "Debt '2' for user 'johndoe' does not exist." }

## Debts Collection [/users/{id}/debts{?checksum}]
Collection of all Debts that this User owes and is owed to another User.

The Debts Collection resource has the following attribute:

- total -- Total number of Balances
- debts -- Array of Debts

+ Parameters
    + id (string, required, `john`) ... ID of the User
    + checksum (string, required, `abcd`) ... Digital signature of the id

+ Model (application/json)

    ```js
    {
        "total": 2,
        "debts": 
        [
            {
                "debtId": 1,
                "user": "janeroe",
                "value": 100,
                "date": "2014-04-14T11:29Z",
                "resolved": true
            },
            {
                "debtId": 2,
                "user": "smith",
                "value": -5.51,
                "date": "2014-04-16T08:30Z",
                "resolved": false
            }
        ]
    }
    ```

### List all Debts of a User [GET]
This method is only available for the authenticated user.

+ Response 200 (application/json)

    [Debts Collection][]
    
+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

### Create a new Debt of a User [POST]
This method is only available for the authenticated user.

+ Parameters

    + checksum (string, required, `abcd`) ... Digital signature of the user and value

+ Request (application/json)

        {
            "user": "johndoe",
            "value": 100
        }

+ Response 201 (application/json)

        {
            "debtId": 2,
            "user": "johndoe",
            "value": 100,
            "date": "2014-04-14T11:29Z",
            "resolved": true
        }

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

+ Response 404 (application/json)

        { "error": "User 'johndoe' does not exist." }
        or
        { "error": "Value '0.0001' is invalid." }

## Balances Collection [/users/{id}/balances{?checksum}]
Collection of all Debts that this User owes and is owed by other Users.

This is a read-only collection and the returned data already contains all the calculations (hence the name *balance*).

The Balances Collection resource has the following attribute:

- total -- Total number of Balances
- balances -- Array of Balances

+ Parameters
    + id (string, required, `john`) ... ID of the User
    + checksum (string, required, `abcd`) ... Digital signature of the id

+ Model (application/json)

    ```js
    {
        "total": 1,
        "balances": 
        [
            {
                "balanceId": 1,
                "user": "janeroe",
                "value": 100,
                "history":
                [
                    { "debtId": 5, "user": "janeroe", "value": 150, "date": "2014-04-14T11:29Z" },
                    { "debtId": 6, "user": "smith", "value": -50, "date": "2014-04-15T08:30Z" }
                ]
            }
        ]
    }
    ```

### List all Balances of a User [GET]
This method is only available for the authenticated user.

+ Response 200 (application/json)

    [Balances Collection][]
    
+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

## Friend [/users/{id}/friends/{friendId}{?checksum}]
A single Friend object. The Friend resource represents a friend of a User.

The Friend resource has the following attributes:

- id -- Username of a Friend

+ Parameters
    + id (string, required, `john`) ... ID of the User
    + friendId (string, required, `jane`) ... ID of a Friend of a User
    + checksum (string, required, `abcd`) ... Digital signature of id and friendId

+ Model (application/json)

    ```js
    {
        "id": "johndoe"
    }
    ```

### Retrieve a single Friend [GET]
This method is only available for the authenticated user.

+ Response 200 (application/json)

    [Friend][]

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

+ Response 404 (application/json)

        { "error": "User 'johndoe' does not exist or is not a friend." }

### Delete a single Friend [DELETE]
This method is only available for the authenticated user.

+ Response 204

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

+ Response 404 (application/json)

        { "error": "User 'johndoe' does not exist or is not a friend." }

## Friends Collection [/users/{id}/friends{?checksum}]
Collection of all Users that are Friends of a User.

This is a one-way only friendship and it is used to provide quick access to Users that are commonly used in the transactions.

The Friends Collection resource has the following attributes:

- total -- Total number of Friends
- friends -- Array of Friends (not detailed)

+ Parameters
    + id (string, required, `john`) ... ID of the User
    + checksum (string, required, `abcd`) ... Digital signature of the id

+ Model (application/json)

    ```js
    {
        "total": 2,
        "friends": 
        [
            { "id": "janeroe" },
            { "id": "smith" }
        ]
    }
    ```

### List all Friends of a User [GET]
This method is only available for the authenticated user.

+ Response 200 (application/json)

    [Friends Collection][]

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

### Create a Friend of a User [POST]
This method is only available for the authenticated user.

+ Request (application/json)

        { "id": "johndoe" }

+ Response 201 (application/json)

        { "id": "johndoe" }

+ Response 403 (application/json)

        { "error": "User 'johndoe' already friended." }
        or
        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

+ Response 404 (application/json)

        { "error": "User 'johndoe' does not exist." }

### Delete all Friends of a User [DELETE]
This method is only available for the authenticated user.

+ Response 204

+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

## Users Collection [/users{?search, checksum}]
Collection of all Users.

The User Collection resource has the following attribute:

- total -- Total number of Users
- Users -- Array of Users (not detailed)

### List all Users [GET]
+ Parameters

    + search (string, optional, `jo`) ... Fuzzy search. Only users that have an *id* or *email* related to the *search* parameter are returned.
    + checksum (string, optional, `abcd`) ... Digital signature of the search if it exists

+ Response 200 (application/json)

        {
            "total": 2,
            "users": 
            [
                { "id": "johndoe" },
                { "id": "janeroe" }
            ]
        }
        
+ Response 403 (application/json)

        { "error": "No permission" }
        or
        { "error": "Invalid checksum" }

### Create a User [POST]

+ Parameters

    + checksum (string, required, `abcd`) ... Digital signature of the id, email and passwordHash

+ Request (application/json)

        { "id": "smith", "email": "smith@example.com", "passwordHash": "abcdef" }

+ Response 201 (application/json)

        { "id": "smith", "email": "smith@example.com" }

+ Response 403 (application/json)

        { "error": "User 'smith' already exists." }
        or
        { "error": "Email 'smith@example.com' already exists." }
        or
        { "error": "Invalid checksum" }
